### ISSUE TITLE
Gem "rubigen" is needed but not being installed as a dependency

### ISSUE THREAD

**Issue by kronn** [toy/sdoc_all#5]
no such file to load -- rubigen (LoadError)

a simple "sudo gem install rubigen" resolved it.

**Comment by toy** [comment]
but gem has depency on rubyigen

so it should be automatically installed when sdoc_all is installed via "[sudo] gem install sdoc_all"

**Comment by kronn** [comment]
I installed sdoc_all version 1.0.2.2 from gemcutter. The gemspec does not include rubigen.
I can see that the github repo includes the dependency declaration in the Rakefile, but the commit is newer than the latest published gem.

The issue is solved for me (I had it working within no time anyway), with the next release to gemcutter it will be solved for everybody :-)

You already know that, but: GREAT WORK. Thanks for _sdoc_all_. It's a huge time-saver.

**Comment by toy** [comment]
I found what has happened: I don't know why, but last version (1.0.3) was not published; it beyond other things fixed absence of depency on rubyigen.
I am glad that my work helps you :)

**Comment by kronn** [comment]
thanks again.

"Help" is an understatement. It allowed me to work offline and have all the documentation available. 

Thanks for pushing the new version to gemcutter! I am currently rebuilding all my docs :-)

**Comment by toy** [comment]
I think issue is closed )
Version 1.0.5 is more about fixing specs and compatibility with ruby 1.9

**Comment by kronn** [comment]
Of course it's closed. 
I meant to click on "Comment and close", sorry if I didn't.

**Comment by toy** [comment]
:)
